/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TasksController_list"];
        put?: never;
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["TasksController_update"];
        post?: never;
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrgsController_getOrgs"];
        put?: never;
        post: operations["OrgsController_createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrgsController_getOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrgsController_listMembers"];
        put?: never;
        post: operations["OrgsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["OrgsController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTaskDto: {
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            orgId: string;
            /** @example My Task */
            title: string;
            /** @example My Task Description */
            description?: string;
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            assigneeId?: string;
        };
        TaskResponseDto: {
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            id: string;
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            orgId: string;
            /** @example My Task */
            title: string;
            /** @example My Task Description */
            description?: string;
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            assigneeId?: string;
            /**
             * @example pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed";
            /**
             * Format: date-time
             * @example 2022-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        UpdateTaskDto: {
            /** @example My Task */
            title?: string;
            /** @example My Task Description */
            description?: string;
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            assigneeId?: string;
            /**
             * @example completed
             * @enum {string}
             */
            status?: "pending" | "in_progress" | "completed";
        };
        CreateOrgDto: {
            /** @example My Org */
            name: string;
        };
        CreateOrgResponseDto: {
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            id: string;
            /** @example My Org */
            name: string;
            /**
             * Format: date-time
             * @example 2022-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        AddMemberDto: {
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            userId: string;
            /**
             * @example viewer
             * @enum {string}
             */
            role: "owner" | "admin" | "viewer";
        };
        MembershipResponseDto: {
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            id: string;
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            orgId: string;
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            userId: string;
            /**
             * @example viewer
             * @enum {string}
             */
            role: "owner" | "admin" | "viewer";
            /**
             * Format: date-time
             * @example 2022-01-01T00:00:00.000Z
             */
            addedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TasksController_list: {
        parameters: {
            query: {
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"][];
                };
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
        };
    };
    AuditController_list: {
        parameters: {
            query: {
                orgId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrgsController_getOrgs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponseDto"][];
                };
            };
        };
    };
    OrgsController_createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponseDto"];
                };
            };
        };
    };
    OrgsController_getOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponseDto"];
                };
            };
        };
    };
    OrgsController_listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"][];
                };
            };
        };
    };
    OrgsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"];
                };
            };
        };
    };
    OrgsController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponseDto"];
                };
            };
        };
    };
}
