// Auto-generated by `tools/generate-openapi-types.js`
import createClient from 'openapi-fetch';
import type { paths } from './api.types.ts';

export const apiClient = createClient<paths>({
  baseUrl: 'http://localhost:3000',
});
