/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example john@example.com */
            email: string;
            /** @example Abcd1234. */
            password: string;
            /** @example John Doe */
            displayName?: string;
        };
        RegisterResponseDto: {
            /** @example edb02073-7032-4674-871c-b4f356447cdf */
            id: string;
            /** @example john@example.com */
            email: string;
            /** @example John Doe */
            displayName: string;
            /**
             * Format: date-time
             * @example 2022-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        LoginDto: {
            /** @example john@example.com */
            email: string;
            /** @example Abcd1234. */
            password: string;
        };
        LoginResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNmEzMjgzZC02MjllLTRhNmQtOTA5MC05MTg1YmQ0ZDY1MDAiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJuYW1lIjpudWxsLCJpYXQiOjE3NTQ5MTUwMDcsImV4cCI6MTc1NDkxODYwN30.TyGnWwYSfL4W05EKG_mwcmjTf_GH_1Iwu-kpN-tTk3Q */
            access_token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Register a new user */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login (returns JWT) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
}
