// Auto-generated by `tools/generate-openapi-types.js`
import createClient from 'openapi-fetch';
import type { paths } from './auth.types.ts';

export const authClient = createClient<paths>({
  baseUrl: 'http://localhost:3001',
});
